{% set name = "git-changelog" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/git_changelog-{{ version }}.tar.gz
  sha256: 2d211a58213eaa97c73be895821c9d4c9242748eb56753f4759c0d24fe493b77

build:
  noarch: python
  entry_points:
    - git-changelog = git_changelog.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - appdirs >=1.4
    - jinja2 >=2.10
    - semver >=2.13
    - tomli >=2.0

test:
  imports:
    - git_changelog
  commands:
    - pip check
    - git-changelog --help
  requires:
    - pip

about:
  summary: Automatic Changelog generator using Jinja2 templates.
  home: https://pawamoy.github.io/git-changelog/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
